name: Test Action

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  hello:
    name: Hello World Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Hello
        run: echo "Hello from test action!"
